version: "2.1"

services:
  webthings-gateway:
    image: webthingsio/gateway:latest
    restart: unless-stopped
    #network_mode: host
    # "ports" are ignored because of "network_mode: host". Either use "ports"
    # or "network_mode: host".
    ports:
      - "8080:8080"
      - "4443:4443"
    volumes:
      - webthings-gateway:webthings
    # If certain devices are needed, e.g. USB dongles, enable them here.
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0
    # If Bluetooth, the container needs to run in privileged mode.
    privileged: true
